runtime: python38 # or another supported version

instance_class: F1

env_variables:
  MYSQL_USER: 'root'
  MYSQL_PASSWORD:
  MYSQL_DB: 'todolist'
  MYSQL_HOST: 'localhost'

handlers:
- url: /img
  static_dir: static/img

- url: /script
  static_dir: static/script

- url: /styles
  static_dir: static/styles